name: pyflct
channels:
  - conda-forge
dependencies:
  - graphviz!=2.42.*
  - pip
  - python=3.9
  - fftw
  - gcc_linux-64
  - pip:
    - matplotlib
    - sphinx
    - sphinx-automodapi
    - sphinx-changelog
    - sphinx-gallery
    - sunpy-sphinx-theme
